"""initial

Revision ID: ef6ed8ad2bfa
Revises: 
Create Date: 2026-04-27 17:30:46.699889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef6ed8ad2bfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_call_log_provider'), 'api_call_log', ['provider'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alfa_crm_id', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('segment', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('interested', sa.Boolean(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', name='uq_leads_phone')
    )
    op.create_index(op.f('ix_leads_alfa_crm_id'), 'leads', ['alfa_crm_id'], unique=True)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('onlinepbx_extension', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_onlinepbx_extension'), 'managers', ['onlinepbx_extension'], unique=False)
    op.create_table('dashboard_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_users_email'), 'dashboard_users', ['email'], unique=True)
    op.create_table('manager_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('onlinepbx_id', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('recording_url_remote', sa.Text(), nullable=True),
    sa.Column('recording_url_cloudinary', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_calls_manager_id'), 'manager_calls', ['manager_id'], unique=False)
    op.create_index(op.f('ix_manager_calls_onlinepbx_id'), 'manager_calls', ['onlinepbx_id'], unique=True)
    op.create_index(op.f('ix_manager_calls_phone'), 'manager_calls', ['phone'], unique=False)
    op.create_index(op.f('ix_manager_calls_started_at'), 'manager_calls', ['started_at'], unique=False)
    op.create_table('whatsapp_sends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(length=128), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('green_api_message_id', sa.String(length=64), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('green_api_message_id')
    )
    op.create_index(op.f('ix_whatsapp_sends_lead_id'), 'whatsapp_sends', ['lead_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_sends_sent_at'), 'whatsapp_sends', ['sent_at'], unique=False)
    op.create_table('zvonar_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('voximplant_session_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voximplant_session_id')
    )
    op.create_index(op.f('ix_zvonar_calls_lead_id'), 'zvonar_calls', ['lead_id'], unique=False)
    op.create_index(op.f('ix_zvonar_calls_started_at'), 'zvonar_calls', ['started_at'], unique=False)
    op.create_table('call_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('funnel_stage', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['manager_calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_summaries_call_id'), 'call_summaries', ['call_id'], unique=True)
    op.create_table('llm_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('criterion', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['manager_calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_scores_call_id'), 'llm_scores', ['call_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['manager_calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_call_id'), 'transcripts', ['call_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_call_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_llm_scores_call_id'), table_name='llm_scores')
    op.drop_table('llm_scores')
    op.drop_index(op.f('ix_call_summaries_call_id'), table_name='call_summaries')
    op.drop_table('call_summaries')
    op.drop_index(op.f('ix_zvonar_calls_started_at'), table_name='zvonar_calls')
    op.drop_index(op.f('ix_zvonar_calls_lead_id'), table_name='zvonar_calls')
    op.drop_table('zvonar_calls')
    op.drop_index(op.f('ix_whatsapp_sends_sent_at'), table_name='whatsapp_sends')
    op.drop_index(op.f('ix_whatsapp_sends_lead_id'), table_name='whatsapp_sends')
    op.drop_table('whatsapp_sends')
    op.drop_index(op.f('ix_manager_calls_started_at'), table_name='manager_calls')
    op.drop_index(op.f('ix_manager_calls_phone'), table_name='manager_calls')
    op.drop_index(op.f('ix_manager_calls_onlinepbx_id'), table_name='manager_calls')
    op.drop_index(op.f('ix_manager_calls_manager_id'), table_name='manager_calls')
    op.drop_table('manager_calls')
    op.drop_index(op.f('ix_dashboard_users_email'), table_name='dashboard_users')
    op.drop_table('dashboard_users')
    op.drop_index(op.f('ix_managers_onlinepbx_extension'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_alfa_crm_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_api_call_log_provider'), table_name='api_call_log')
    op.drop_table('api_call_log')
    # ### end Alembic commands ###
